import React, { useEffect, useState } from 'react';
import { QrCode, PackageCheck } from 'lucide-react';
import { QRCodeSVG } from 'qrcode.react';
import api from '../../utils/api';

const blank = { building_id: '', name: '', asset_code: '', category: '', location: '', description: '' };

export default function Assets() {
  const [sites, setSites] = useState([]); const [site, setSite] = useState(''); const [assets, setAssets] = useState([]); const [form, setForm] = useState(blank); const [qr, setQr] = useState(null); const [message, setMessage] = useState('');
  const loadSites = async () => { const res = await api.get('/buildings'); const values = res.data.buildings || []; setSites(values); if (values[0]) setSite(values[0].id); };
  const loadAssets = () => site && api.get(`/operations/assets/${site}`).then(res => setAssets(res.data.assets || [])).catch(console.error);
  useEffect(() => { loadSites().catch(console.error); }, []); useEffect(() => { loadAssets(); }, [site]);
  const submit = async e => { e.preventDefault(); try { const res = await api.post('/operations/assets', { ...form, building_id: site }); setMessage('Asset created. Print its QR label before the patrol trial.'); setQr(res.data.asset); setForm(blank); loadAssets(); } catch (err) { setMessage(err.response?.data?.error || 'Unable to create asset'); } };
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-white">Asset & Patrol Tags</h1><p className="text-[#888] mt-1">Create a QR label for every asset or mandatory patrol checkpoint.</p></div><select className="field max-w-md" value={site} onChange={e => setSite(e.target.value)}>{sites.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><div className="grid lg:grid-cols-3 gap-6"><form onSubmit={submit} className="bg-[#111111] border border-[#1f1f1f] rounded-2xl p-6 space-y-3"><h2 className="font-semibold text-white">Create asset tag</h2>{message && <p className="text-sm text-[#d4ae2a]">{message}</p>}<input className="field" required placeholder="Asset or checkpoint name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /><input className="field" required placeholder="Unique asset code" value={form.asset_code} onChange={e => setForm({ ...form, asset_code: e.target.value })} /><input className="field" placeholder="Category" value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} /><input className="field" placeholder="Location / zone" value={form.location} onChange={e => setForm({ ...form, location: e.target.value })} /><textarea className="field" placeholder="Notes" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /><button className="w-full bg-[#d4ae2a] text-black font-semibold py-3 rounded-xl hover:bg-[#e8c847] transition">Create QR tag</button></form><div className="lg:col-span-2 grid sm:grid-cols-2 gap-4">{assets.map(asset => <div className="bg-[#111111] border border-[#1f1f1f] rounded-2xl p-5" key={asset.id}><div className="flex justify-between gap-3"><div><p className="font-semibold text-white">{asset.name}</p><p className="text-sm text-[#888]">{asset.asset_code} · {asset.location || 'No location'}</p></div><button onClick={() => setQr(asset)}><QrCode className="text-[#d4ae2a]" /></button></div><span className="inline-block mt-4 text-xs bg-[#1a1a1a] text-[#888] rounded px-2 py-1">{asset.category || 'Uncategorised'}</span></div>)}{!assets.length && <div className="sm:col-span-2 text-[#666] text-center py-16"><PackageCheck className="w-10 h-10 mx-auto mb-3" />No asset tags for this site.</div>}</div></div>{qr && <div className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-4" onClick={() => setQr(null)}><div className="bg-white p-7 rounded-2xl text-center" onClick={e => e.stopPropagation()}><h2 className="font-bold text-white">{qr.name}</h2><p className="text-sm text-[#666] my-2">{qr.asset_code}</p><QRCodeSVG value={`asset:${qr.id}`} size={240} /><p className="text-xs text-[#666] mt-3">Print and attach this QR label to the asset or checkpoint.</p><button onClick={() => window.print()} className="mt-5 px-4 py-2 bg-[#d4ae2a] text-black font-semibold rounded-xl hover:bg-[#e8c847] transition">Print label</button></div></div>}</div>;
}
