import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, ClipboardCheck, CheckCircle2 } from 'lucide-react';
import api from '../../utils/api';
import { useAuth } from '../../context/AuthContext';

export default function Patrol() {
  const { user } = useAuth(); const navigate = useNavigate(); const [patrol, setPatrol] = useState(null); const [detail, setDetail] = useState(null); const [code, setCode] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { const saved = localStorage.getItem(`active_patrol_${user?.id}`); if (saved) load(saved); }, [user]);
  const load = async id => { try { const res = await api.get(`/operations/patrols/${id}`); setPatrol(res.data.patrol); setDetail(res.data); } catch { localStorage.removeItem(`active_patrol_${user?.id}`); } };
  const start = async () => { try { const res = await api.post('/operations/patrols', { building_id: user.building_id }); localStorage.setItem(`active_patrol_${user.id}`, res.data.patrol_id); load(res.data.patrol_id); } catch (err) { setMessage(err.response?.data?.error || 'Unable to start patrol'); } };
  const scan = async e => { e.preventDefault(); try { await api.post(`/operations/patrols/${patrol.id}/scans`, { asset_qr: code }); setCode(''); setMessage('Asset verified.'); load(patrol.id); } catch (err) { setMessage(err.response?.data?.error || 'Asset verification failed'); } };
  const complete = async () => { try { await api.post(`/operations/patrols/${patrol.id}/complete`); localStorage.removeItem(`active_patrol_${user.id}`); setMessage('Patrol completed successfully.'); setPatrol(null); setDetail(null); } catch (err) { setMessage(err.response?.data?.error || 'All checkpoints must be scanned before completion'); } };
  return <div className="min-h-screen bg-slate-950 text-white"><header className="bg-slate-900 border-b border-slate-800 p-4"><div className="max-w-lg mx-auto flex items-center gap-3"><button onClick={() => navigate('/staff')} className="p-2 bg-slate-800 rounded-xl"><ArrowLeft className="w-5 h-5" /></button><div><p className="font-bold">Asset Patrol</p><p className="text-xs text-slate-400">Verify every required checkpoint</p></div></div></header><main className="max-w-lg mx-auto p-4">{message && <p className="bg-indigo-500/10 border border-indigo-500/30 p-3 rounded-xl text-sm text-indigo-200">{message}</p>}{!patrol ? <div className="text-center bg-slate-900 rounded-3xl border border-slate-800 p-8 mt-6"><ClipboardCheck className="w-14 h-14 text-indigo-400 mx-auto mb-4" /><h1 className="text-xl font-bold">Ready to begin?</h1><p className="text-slate-400 text-sm mt-2">Start a round, then scan every client asset or checkpoint QR label.</p><button onClick={start} className="mt-6 w-full py-3 bg-indigo-600 rounded-xl font-semibold">Start patrol</button></div> : <><div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 mt-5"><div className="flex justify-between"><div><p className="font-semibold">Patrol in progress</p><p className="text-sm text-slate-400">{detail?.patrol.site_name}</p></div><p className="text-2xl font-bold text-indigo-300">{detail?.progress.scanned}/{detail?.progress.required}</p></div></div><form onSubmit={scan} className="mt-4 flex gap-2"><input autoFocus className="field flex-1" value={code} onChange={e => setCode(e.target.value)} placeholder="Scan or enter asset QR value" /><button className="px-4 bg-indigo-600 rounded-xl">Verify</button></form><div className="mt-5 space-y-2">{detail?.checkpoints.map(checkpoint => <div key={checkpoint.id} className="p-4 bg-slate-900 border border-slate-800 rounded-xl flex justify-between items-center"><div><p className="font-medium">{checkpoint.name}</p><p className="text-xs text-slate-400">{checkpoint.location || checkpoint.asset_code}</p></div>{checkpoint.scan ? <CheckCircle2 className="text-emerald-400" /> : <span className="text-xs text-slate-500">Pending</span>}</div>)}</div><button onClick={complete} className="w-full mt-6 py-3 bg-emerald-600 rounded-xl font-semibold">Complete patrol</button></>}</main></div>;
}
